version : “3”
services :
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 888:888
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  web:
    build: .
    scale: 3
    image: "nodejstest"
