apiVersion: v1
kind: Service
metadata:
  name: nodejsservice
spec:
  selector:
    app: nodejs
  type: NodePort
  ports:
     - protocol: TCP
       port: 1234
       targetPort: 1234
       nodePort: 30008